### ISSUE TITLE
Kinda Malware

### ISSUE THREAD

**Issue by AdvDebug** [ccman32/WMISpoofer#5]
This Program i tested it in a vm and it injects a dll in LITERALLY EVERY PROCESS, i understand that this maybe because it spoofs WMI This way, but that's not the way you do it, you let the user specify the process or you should notify the user that you will inject dll into every process, and it adds itself to autorun using this registry key: HKEY_LOCAL_MACHINE\SOFTWARE\MICROSOFT\WINDOWS NT\CURRENTVERSION\WINDOWS --> AppInit_DLLs (string), it even injects itself to firefox, please fix your program.

**Comment by ccman32** [comment]
The whole point of this application was to enable system-wide spoofing of WMI related data. Therefore, it is absolutely necessary for it to be able to control everything that could possibly access the WMI (at least in user space). This application was never intended to be used for specific processes only. In fact, I wrote this in the context of developing a solution targeted at VMs for hiding every piece of information that could expose the fact that Windows is running inside a VM. This was meant to be used for scam baiting where it is a common practice to let scammers waste their time on VMs so they cannot scam other people in the meanwhile. In situations like that, scammers often use tools such as msinfo32 or wmic to check for system properties indicating that the system is actually running on a VM. Sometimes they even develop small scripts or simple applications which they run on the victims computer, so a solution that only targets specific processes would not work in this case. While there are certainly better ways to do this, injecting the WMI spoofing code into every process via AppInit_DLLs was one of the easiest and most time efficient ways to get the job done back when I was working on this project. As I already left the scam baiting scene for the most part, I am no longer working on this project. However, feel free to fork and edit/improve it in any way you want to fit your needs. Finally, this is a very niche project and I expect a certain technical background and understanding from someone working with/on it. Therefore, I do not feel the need to make it any less invasive or implement any sort of warnings into it. Additionally, it is very easy to uninstall without causing any permanent damage to the system.
